### ISSUE TITLE
Targets that are not on active pixels report as being observable

### ISSUE THREAD

**Issue by mrtommyb** [christopherburke/tess-point#10]
The tool accurately reports the coordinates, but does not warn if pixels are not active. It would be good if in the readme could list the active pixels. 
Perhaps even print a warning if pixels are close to the edge of the CCD?

I can't actually find in the instrument handbook what the active pixel values are.

**Comment by christopherburke** [comment]
This sounds like a good addition.  I will work on it for the next release.
The active pixels are described/hidden in caption of Fig. 4.3 on instrument handbook, but tess-point can provide some guidance on this as well.

**Comment by mrtommyb** [comment]
Ah yes, thanks Chris.

**Comment by christopherburke** [comment]
I may have read this request wrong.  But the latest v0.6.1 now has an output edge warning flag in column 11.  If the target is within 6 pixels of the science active pixels, target management will not allow the target to be assigned a 2 minute or 20 sec aperture.  The edgeWarn==1 flag indicates if the target is on science silicon, but within 6 pixels of the edge and is in danger of being too close to the edge to be assigned an aperture. The readme now gives which pixels are active science pixels.

tess-point has always only listed a target if it predicted to be on the science region. Un rereading your request this addition may not be what you wanted Is this request to allow for showing targets that are not predicted to be on silicon, but are close?  Like if the target is within 3 pixels of the active pixels, but not on them do you want to print it out as being close?
