### ISSUE TITLE
Shouldn't install in python2

### ISSUE THREAD

**Issue by doctormo** [christopherburke/tess-point#3]
Because the system requires astropy, it should limit itself to python3 only since astropy is now python3 only.

Astropy should be added to the requirements like numpy.

**Comment by christopherburke** [comment]
I gave it one last google foo go, and I found out how to specify python version dependent requirements in setup.py.  This is what I used
    install_requires=[
        'numpy',
        'astropy<=2.0.7;python_version<="2.7"',
        'astropy;python_version>"2.7"',
        'scipy'
    ]
This has been pushed to v0.3.1, so try
pip install tess-point --upgrade
and let me know if this issue can be closed.  Cheers!

**Comment by christopherburke** [comment]
Ignore that last comment.
install_requires=[
'numpy',
'astropy',
'scipy'
]
is all that is needed in setup.py.  I was testing incorrectly, and one should just trust in pip.
