### ISSUE TITLE
Different results than those of Web TESS Viewing Tool 

### ISSUE THREAD

**Issue by jdavidrcamacho** [christopherburke/tess-point#7]
While using the Web TESS Viewing Tool on the star CD-571633 (ra = 106.62063241; dec = -57.45808835), the webpage shows me the star was observed in sector 1 to 13 continuously and will be observed in sector 27 to 39 continuously.

When using your example_use_tess_stars2py_byfunction.py file, and simply substituting the ra and dec of your first example by the coordinates of my star print in my console gives

```
261136679 2 4 4 869.227523 231.632411
261136679 3 4 4 1639.103566 854.091831
261136679 4 4 4 2033.202936 1760.895104
261136679 5 4 1 171.827387 1463.471022
261136679 6 4 1 675.880113 631.109477
261136679 7 4 1 1493.320717 123.083628
261136679 8 4 2 273.865405 37.861225
261136679 9 4 2 1150.828203 373.966626
261136679 10 4 2 1795.823184 1071.893321
261136679 12 4 3 271.944677 1222.705882
261136679 13 4 3 896.763409 454.664541
261136679 27 4 3 1346.619298 195.872932
261136679 28 4 4 68.139245 35.994418
261136679 29 4 4 970.578021 282.675051
261136679 30 4 4 1702.158784 941.620929
261136679 32 4 1 239.446296 1281.110132
261136679 33 4 1 857.360942 468.377127
261136679 34 4 1 1753.870819 54.499106
261136679 35 4 2 540.928713 92.985784
261136679 36 4 2 1357.994228 533.815144
261136679 37 4 2 1901.157048 1285.828917
261136679 38 4 3 76.152191 1980.765652
```

Where, if I'm interpreting the results correctly, is missing sectors 1, 11, 31, and 39.

The missing 39th sector I believe it comes from line 726 of the tess_stars2px.py file where you have `sectors = np.arange(1,39, dtype=np.int)` it should be s`ectors = np.arange(1,40, dtype=np.int)`.
The other missing sectors I don't know exactly what is going on.
Do you think the mistake is in the web page or this package?

Cheers
Camacho

**Comment by christopherburke** [comment]
Thank you for finding these problems.  The sector list was incorrect, and now sector 39 will be included.  Also, the function entry was out of date for checking the boundaries of the detectors.  The boundary check was fixed for the normal tess_stars2px.py from command line in an earlier release.  But the old boundary check code was not modified in the function entry version. In other words had nearly duplicate code in two places and one got fixed and the other did not.  Let me know if you continue to have problems.  'pip install --upgrade tess-point' will get you to the v0.3.9 with these fixes.
