### ISSUE TITLE
Best way to cite tess-point?

### ISSUE THREAD

**Issue by benmontet** [christopherburke/tess-point#8]
Hi Chris! 

I'm using tess-point in a project and would like to cite it. I currently have a footnote to the github link, but is there a different official recommended way to cite the package? I don't see anything in the docs. I would like to do something that you can count in the traditional metrics, which in my mind would mean a DOI that's tracked by ADS like you would get through a submission to [ASCL](https://ascl.net/) or [JOSS](https://joss.theoj.org/). Do you have plans to submit this package to either of those, or is linking the github and including it in the \software tag the recommended method?

Thank you!

**Comment by christopherburke** [comment]
Hi Ben,
  I haven't done an ASCL submission before, but it does sound like it would be helpful to have a citable for tess-point.  I will work on a codemeta.json file and circulate to authors and contributors for this software.  I'll keep you posted.  Thank you for your interest in the code and helping the TESS community.

**Comment by benmontet** [comment]
Cool, sounds good! Let me know if there's anything I can do to be helpful. FWIW, in my experience the ASCL folks have been extremely easy to work with. 

My paper draft is not close to submission so from my perspective there's absolutely no rush, although I'm surely not the only person using tess-point regularly!

**Comment by christopherburke** [comment]
We now have an ASCL assignment
http://www.ascl.net/2003.001
Thank you for suggesting this citation mechanism.
I will update the README to add this citation information.
